---

- name: auth-windows | Install auth windows dependencies
  apt: pkg=$item state=installed
  with_items:
    - samba 
    - libpam-smbpass
  tags: auth





#- name: auth-client | ensure krb5.conf exists
#  template: src=root/etc/krb5.conf.j2 dest=/etc/krb5.conf owner=root group=root
#  tags: auth auth-client krb
#
#- name: auth-client | ensure nsswitch.conf exists
#  template: src=root/etc/nsswitch.conf.j2 dest=/etc/nsswitch.conf owner=root group=root
#  tags: auth auth-client
#
#- name: auth-client | ensure /etc/polkit-1/localauthority.conf.d exists
#  file: path=/etc/polkit-1/localauthority.conf.d/ state=directory owner=root group=root
#  tags: auth auth-client
#
#- name: auth-client | ensure 51-ubuntu-admin.conf exists
#  template: src=root/etc/polkit-1/localauthority.conf.d/51-ubuntu-admin.conf.j2 dest=/etc/polkit-1/localauthority.conf.d/51-ubuntu-admin.conf owner=root group=root
#  tags: auth auth-client
#
#- name: auth-client | ensure /etc/lightdm exists
#  file: path=/etc/lightdm/lightdm.conf state=directory owner=root group=root
#  tags: auth auth-client
#
#- name: auth-client | ensure lightdm.conf exists
#  template: src=root/etc/lightdm/lightdm.conf.j2 dest=/etc/lightdm/lightdm.conf owner=root group=root
#  tags: auth auth-client
#
#- name: auth-client | configure sudoers to allow domainadmins
#  template: src=root/etc/sudoers.d/domainadmins dest=/etc/sudoers.d/domainadmins owner=root group=root mode=0440
#  tags: auth-client auth
#
#- name: auth-client | Ensure imapd is configured
#  template: src=root/etc/idmapd.conf.j2 dest=/etc/idmapd.conf owner=root group=root mode=0644
#  notify:
#    - restart idmapd
#  tags: auth auth-client idmapd
